{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 0,
  "build_id": "v0.98.1",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.NIBBITS_NORMAL",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GOLDEN_PEARL",
                "title": {
                  "key": "GOLDEN_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LARGE_CAPSULE",
                "title": {
                  "key": "LARGE_CAPSULE.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.STRIKE_IRONCLAD"
              },
              {
                "id": "CARD.DEFEND_IRONCLAD"
              }
            ],
            "current_gold": 99,
            "current_hp": 80,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LARGE_CAPSULE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 80,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LARGE_CAPSULE",
                "was_picked": true
              },
              {
                "choice": "RELIC.STONE_CALENDAR",
                "was_picked": true
              },
              {
                "choice": "RELIC.PANTOGRAPH",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFERNAL_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              }
            ],
            "current_gold": 114,
            "current_hp": 74,
            "damage_taken": 12,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.LEAF_SLIME_S",
              "MONSTER.TWIG_SLIME_M",
              "MONSTER.TWIG_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JUGGLING"
                },
                "was_picked": false
              }
            ],
            "current_gold": 129,
            "current_hp": 72,
            "damage_taken": 8,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.POMMEL_STRIKE"
              }
            ],
            "current_gold": 140,
            "current_hp": 72,
            "damage_taken": 6,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOOD_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.MANGLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ANGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MANGLE"
              }
            ],
            "current_gold": 152,
            "current_hp": 56,
            "damage_taken": 22,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SNAPPING_JAXFRUIT_NORMAL",
            "monster_ids": [
              "MONSTER.SNAPPING_JAXFRUIT",
              "MONSTER.FLYCONID"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 152,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.MANGLE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.DISMANTLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MOLTEN_FIST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DISMANTLE"
              }
            ],
            "current_gold": 192,
            "current_hp": 18,
            "damage_taken": 60,
            "gold_gained": 40,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.GAMBLERS_BREW",
              "POTION.BLOOD_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.SPARKLING_ROUGE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 192,
            "current_hp": 4,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "current_gold": 192,
            "current_hp": 0,
            "damage_taken": 4,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_NORMAL",
            "monster_ids": [
              "MONSTER.NIBBIT",
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.IRONCLAD",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.POMMEL_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.MANGLE"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.DISMANTLE"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 3,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BURNING_BLOOD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.LARGE_CAPSULE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.STONE_CALENDAR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.PANTOGRAPH"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.SPARKLING_ROUGE"
        },
        {
          "floor_added_to_deck": 8,
          "id": "RELIC.CHOSEN_CHEESE"
        }
      ]
    }
  ],
  "run_time": 396,
  "schema_version": 8,
  "seed": "PX12F2M7BR",
  "start_time": 1772842753,
  "was_abandoned": false,
  "win": false
}