{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 4,
  "build_id": "v0.98.2",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "BOOMING_CONCH",
                "title": {
                  "key": "BOOMING_CONCH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SCROLL_BOXES",
                "title": {
                  "key": "SCROLL_BOXES.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ULTIMATE_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SEEKER_STRIKE"
              }
            ],
            "current_gold": 99,
            "current_hp": 64,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 64,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LEAD_PAPERWEIGHT",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BLOOD_WALL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PERFECTED_STRIKE"
              }
            ],
            "current_gold": 113,
            "current_hp": 67,
            "damage_taken": 3,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNRELENTING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STAMPEDE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 122,
            "current_hp": 59,
            "damage_taken": 14,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.REGEN_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.EXPECT_A_FIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JUGGERNAUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.EXPECT_A_FIGHT"
              }
            ],
            "current_gold": 134,
            "current_hp": 61,
            "damage_taken": 9,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 11,
            "max_hp": 85,
            "max_hp_gained": 5,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FRUIT_JUICE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FRUIT_JUICE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 134,
            "current_hp": 67,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WATERLOGGED_SCRIPTORIUM.pages.INITIAL.options.BLOODY_INK.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 91,
            "max_hp_gained": 6,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.WATERLOGGED_SCRIPTORIUM",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.TRUE_GRIT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GRAPPLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TRUE_GRIT"
              }
            ],
            "current_gold": 160,
            "current_hp": 47,
            "damage_taken": 40,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.REGEN_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MEAL_TICKET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TREMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLUDGEON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SHRUG_IT_OFF"
              }
            ],
            "current_gold": 171,
            "current_hp": 30,
            "damage_taken": 23,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FOSSIL_STALKER_NORMAL",
            "monster_ids": [
              "MONSTER.FOSSIL_STALKER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "current_gold": 171,
            "current_hp": 0,
            "damage_taken": 30,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.IRONCLAD",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SEEKER_STRIKE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.PERFECTED_STRIKE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.EXPECT_A_FIGHT"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.TRUE_GRIT"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.SHRUG_IT_OFF"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BURNING_BLOOD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.LEAD_PAPERWEIGHT"
        },
        {
          "floor_added_to_deck": 6,
          "id": "RELIC.MEAL_TICKET"
        }
      ]
    }
  ],
  "run_time": 350,
  "schema_version": 8,
  "seed": "9UWA7J57TC",
  "start_time": 1773090315,
  "was_abandoned": false,
  "win": false
}