{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 10,
  "build_id": "v0.99.1",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.TERROR_EEL_ELITE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "POMANDER",
                "title": {
                  "key": "POMANDER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "NEW_LEAF",
                "title": {
                  "key": "NEW_LEAF.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SILVER_CRUCIBLE",
                "title": {
                  "key": "SILVER_CRUCIBLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.ERADICATE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_NECROBINDER"
                }
              }
            ],
            "current_gold": 99,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NEW_LEAF.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 52,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.NEW_LEAF",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BURY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GRAVE_WARDEN"
              }
            ],
            "current_gold": 114,
            "current_hp": 47,
            "damage_taken": 5,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.AFTERLIFE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SCOURGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.VEILPIERCER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.AFTERLIFE"
              }
            ],
            "current_gold": 121,
            "current_hp": 46,
            "damage_taken": 1,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.NEGATIVE_PULSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEBILITATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAUNT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NEGATIVE_PULSE"
              }
            ],
            "current_gold": 135,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.AFTERLIFE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEATH_MARCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.AFTERLIFE"
              }
            ],
            "current_gold": 143,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POWER_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FOSSIL_STALKER_NORMAL",
            "monster_ids": [
              "MONSTER.FOSSIL_STALKER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.SEANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COUNTDOWN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INVOKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SEANCE"
              }
            ],
            "current_gold": 170,
            "current_hp": 25,
            "damage_taken": 21,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 170,
            "current_hp": 44,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.SCOURGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NEGATIVE_PULSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SCOURGE"
              }
            ],
            "current_gold": 182,
            "current_hp": 34,
            "damage_taken": 10,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LIVING_FOG_NORMAL",
            "monster_ids": [
              "MONSTER.LIVING_FOG"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "current_gold": 182,
            "current_hp": 0,
            "damage_taken": 34,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.FLEX_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.NECROBINDER",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BODYGUARD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.UNLEASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ERADICATE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.GRAVE_WARDEN"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.AFTERLIFE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.NEGATIVE_PULSE"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.AFTERLIFE"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.SEANCE"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.SCOURGE"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BOUND_PHYLACTERY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.NEW_LEAF"
        },
        {
          "floor_added_to_deck": 6,
          "id": "RELIC.VAJRA"
        }
      ]
    }
  ],
  "run_time": 407,
  "schema_version": 8,
  "seed": "9FVHQAVH91",
  "start_time": 1775170931,
  "was_abandoned": false,
  "win": false
}