{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 8,
  "build_id": "v0.99.1",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "STONE_HUMIDIFIER",
                "title": {
                  "key": "STONE_HUMIDIFIER.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "NEOWS_TORMENT",
                "title": {
                  "key": "NEOWS_TORMENT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SILVER_CRUCIBLE",
                "title": {
                  "key": "SILVER_CRUCIBLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 99,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "STONE_HUMIDIFIER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 52,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.STONE_HUMIDIFIER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.CAPTURE_SPIRIT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.NEGATIVE_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEATHS_DOOR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CAPTURE_SPIRIT"
              }
            ],
            "current_gold": 107,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PAGESTORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MIND_BLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MAYHEM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PULL_AGGRO"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              }
            ],
            "current_gold": 8,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 99,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.LUCKY_TONIC",
                "was_picked": false
              },
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PANTOGRAPH",
                "was_picked": false
              },
              {
                "choice": "RELIC.NUNCHAKU",
                "was_picked": false
              },
              {
                "choice": "RELIC.CHEMICAL_X",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.SNAP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEATHS_DOOR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SNAP"
              }
            ],
            "current_gold": 18,
            "current_hp": 46,
            "damage_taken": 6,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 18,
            "current_hp": 32,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "current_gold": 18,
            "current_hp": 0,
            "damage_taken": 32,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.COLORLESS_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.NECROBINDER",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BODYGUARD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.UNLEASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.CAPTURE_SPIRIT"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.PULL_AGGRO"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.SNAP"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BOUND_PHYLACTERY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.STONE_HUMIDIFIER"
        },
        {
          "floor_added_to_deck": 5,
          "id": "RELIC.CHOSEN_CHEESE"
        }
      ]
    }
  ],
  "run_time": 193,
  "schema_version": 8,
  "seed": "91WP3EFT10",
  "start_time": 1775084454,
  "was_abandoned": false,
  "win": false
}